### ISSUE TITLE
ERROR: No matching distribution found for dataclasses==0.8

### ISSUE THREAD

**Issue by Ayusummer** [Lanly109/headimg_generator#1]
python版本:3.8.3

安装依赖时报错:
ERROR: No matching distribution found for dataclasses==0.8

原因:  
[RROR: No matching distribution found for dataclasses==0.8 - Streamlit Cloud - Streamlit](https://discuss.streamlit.io/t/rror-no-matching-distribution-found-for-dataclasses-0-8/11667/3)

![image](https://user-images.githubusercontent.com/59549826/169796364-a350514d-b540-419a-92ac-c47fc9e0be56.png)

解决方案:
新建一个 py38requirements.txt 拷贝原本的 requirements 删去 dataclasses==0.8

除此以外, py38 首次安装依赖时报找不到 dataclasses, 后续删除 dataclasses 后再安装依赖会导致前置依赖冲突, 需要先 pip uninstall -r requirements.txt -y 后再重新 pip install -r requirements.txt

**Comment by Lanly109** [comment]
感谢指出，我会删去该依赖
