### ISSUE TITLE
请问如何使用回复来触发，比如回复一张图`撕`之类的

### ISSUE THREAD

**Issue by SaarChaffee** [Lanly109/headimg_generator#12]

**Comment by Lanly109** [comment]
目前暂时不能，[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)可以，但它使用的api是`nonebot2`才有的reply属性，可以获取被回复消息的图片；而`hoshino`基于的`nonebot1`暂时没有该属性，只能获取到被回复消息的`id`，没研究过能不能依此获取到被回复消息的图片。
在[__init__.py](https://github.com/Lanly109/headimg_generator/blob/main/__init__.py#L53)的第53行注释就是[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)里的对被回复消息图片的处理。

**Comment by SaarChaffee** [comment]
> 目前暂时不能，[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)可以，但它使用的api是`nonebot2`才有的reply属性，可以获取被回复消息的图片；而`hoshino`基于的`nonebot1`暂时没有该属性，只能获取到被回复消息的`id`，没研究过能不能依此获取到被回复消息的图片。 在[**init**.py](https://github.com/Lanly109/headimg_generator/blob/main/__init__.py#L53)的第53行注释就是[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)里的对被回复消息图片的处理。

好的明白了

**Comment by kcn3388** [comment]
调整cqhttp的设置
```yml
# 为Reply附加更多信息
  extra-reply-data: true
```
即可获得回复的消息的文本及cq码

**Comment by SaarChaffee** [comment]
> 

尝试修改设置之后，拿到的内容是
```
[CQ:reply,id=1894547954,seq=2408,qq=我Q号,time=1664040845,text=&amp;#91;图片&amp;#93;][CQ:at,qq=我Q号] 撕
```

**Comment by kcn3388** [comment]
> > 
> 
> 尝试修改设置之后，拿到的内容是
> 
> ```
> [CQ:reply,id=1894547954,seq=2408,qq=我Q号,time=1664040845,text=&amp;#91;图片&amp;#93;][CQ:at,qq=我Q号] 撕
> ```

text里面的图片内容转换为cq码即可

**Comment by kcn3388** [comment]
> 目前暂时不能，[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)可以，但它使用的api是`nonebot2`才有的reply属性，可以获取被回复消息的图片；而`hoshino`基于的`nonebot1`暂时没有该属性，只能获取到被回复消息的`id`，没研究过能不能依此获取到被回复消息的图片。 在[**init**.py](https://github.com/Lanly109/headimg_generator/blob/main/__init__.py#L53)的第53行注释就是[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)里的对被回复消息图片的处理。

可以的，但是当前go-cqhttp的稳定版构建存在bug，回复id获取会出问题，dev分支的最新构建已修复

**Comment by Lanly109** [comment]
> > 目前暂时不能，[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)可以，但它使用的api是`nonebot2`才有的reply属性，可以获取被回复消息的图片；而`hoshino`基于的`nonebot1`暂时没有该属性，只能获取到被回复消息的`id`，没研究过能不能依此获取到被回复消息的图片。 在[**init**.py](https://github.com/Lanly109/headimg_generator/blob/main/__init__.py#L53)的第53行注释就是[原插件](https://github.com/noneplugin/nonebot-plugin-petpet)里的对被回复消息图片的处理。
> 
> 可以的，但是当前go-cqhttp的稳定版构建存在bug，回复id获取会出问题，dev分支的最新构建已修复

好，等会战结束了我研究下。

**Comment by kcn3388** [comment]
> 好，等会战结束了我研究下。

实现方法：
```python
bot.get_msg(msg_id)
```

[文档](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E6%B6%88%E6%81%AF)

**Comment by kcn3388** [comment]
finish in #18

**Comment by Lanly109** [comment]
> finish in #18
> 
> 对于一个完整的reply message，存在一个隐式调用的@cq码；同时当回复对象不是自己时，会自动补充一个显示@，对于PCQQ无法主动删除，移动端则可以手动删除@，因此一个完整的reply最多会重复两次at，因为reply中本身就存在回复对象的QQ，因此这两个@建议删除以防止读错参数

关于移动端和PC端的是不是反了？我自己测试的ios qq和mac qq，显示的at删掉的话，pc端是没有隐式at，而手机端还保留着隐式at

**Comment by kcn3388** [comment]
> > finish in #18
> > 对于一个完整的reply message，存在一个隐式调用的@cq码；同时当回复对象不是自己时，会自动补充一个显示@，对于PCQQ无法主动删除，移动端则可以手动删除@，因此一个完整的reply最多会重复两次at，因为reply中本身就存在回复对象的QQ，因此这两个@建议删除以防止读错参数
> 
> 关于移动端和PC端的是不是反了？我自己测试的ios qq和mac qq，显示的at删掉的话，pc端是没有隐式at，而手机端还保留着隐式at

PC和AndroidQQ可以删除回复时附带的显式at，删除以后你看raw_message还是存在一个隐式的at（因为回复本身就带一个隐式at）
