### ISSUE TITLE
字体相关

### ISSUE THREAD

**Issue by Ayusummer** [Lanly109/headimg_generator#2]
建议将字体文件单独给出
当前仓库比较大,网络不好 git clone 容易失败

**Comment by Ayusummer** [comment]
若删除字体文件,单独给出,后续新增用户clone建议使用 --dept 1 参数 clone 仓库忽略因字体提交占据的.git容量

**Comment by Lanly109** [comment]
好建议，我重新push覆盖掉吧，把字体放到`release`里

**Comment by Ayusummer** [comment]
> 好建议，我重新push覆盖掉吧，把字体放到`release`里

感觉 images 也可以考虑打个包发出来

font 41.2M, images 21.8M 🤔

**Comment by Ayusummer** [comment]
直接将 resource 打包如何呢?

**Comment by Lanly109** [comment]
`image`的话我考虑到后续可能会更新，这样每次新加图片都要下载20+MB？而字体相对来说会稳定点
不过应该也可以打包出来。事实上源代码里对于不存在的图片它会去资源网站上下载~只是最近那个资源网站似乎炸了~
我晚点重新弄弄
