### ISSUE TITLE
bug，爬指令显示cq为空，无法使用自己代替艾特自己

### ISSUE THREAD

**Issue by Fhm-newbie** [Lanly109/headimg_generator#20]
![image](https://user-images.githubusercontent.com/63446200/199378906-efc7fc95-158f-4fd0-a708-23e63d0ed617.png)
![image](https://user-images.githubusercontent.com/63446200/199379573-e9035ec0-1f82-4d3e-ac0c-b86ed37cf840.png)

**Comment by Fhm-newbie** [comment]
![image](https://user-images.githubusercontent.com/63446200/199380653-6fd5c290-cda3-4884-bfc8-8270ccb7ee3e.png)

**Comment by Lanly109** [comment]
`不文明`和`自己`之间需要加一个空格，`自己`应被视为一个参数

**Comment by Fhm-newbie** [comment]
好的，加空格后能正常对自己使用了，之前我记得是不需要加空格的
那那个爬的表情包能请问一下是怎么回事吗？下面这是我用了爬 自己后hoshino的日志输出
![image](https://user-images.githubusercontent.com/63446200/199484352-77275d33-2d45-4210-87f4-fbc153ed7a38.png)

**Comment by Lanly109** [comment]
看看`go-cqhttp`那边的输出是什么？以及您的触发指令是什么？
我这里的`爬`指令挺正常的

**Comment by Fhm-newbie** [comment]
我发现问题了， 爬 这个字眼似乎是被另一个插件叫nonebot语言库的给拦住了，发送 爬 这个字只能触发那个插件的图片。。。我看看自己改一下能不能好使。。。

**Comment by Fhm-newbie** [comment]
已经把那个插件的触发字删掉了，能成功触发了，感谢大佬
