### ISSUE TITLE
代码重构后gif图

### ISSUE THREAD

**Issue by ciriue** [Lanly109/headimg_generator#22]
os：win 2019
log：无报错
代码重构后指令[一直一直][迷惑]以gif图制作表情包第二帧会花：
![image](https://user-images.githubusercontent.com/84818059/203531283-88bae672-4f76-45e3-b77b-dbbb43b3adbf.png)
![@EF% 03N(XO79$}HO22`ZC](https://user-images.githubusercontent.com/84818059/203531418-4c30507c-02e9-4c1e-8374-66fc4b133497.png)
![F0TNOR1GO7W3WBWSMO}0V7P](https://user-images.githubusercontent.com/84818059/203532809-55f0a4e6-da95-4c8f-ade6-d4204a0bb674.png)

原图为静态时不会触发
![image](https://user-images.githubusercontent.com/84818059/203532171-27ed95d5-23ef-496c-8afd-5c66f917f4bd.png)

其他指令暂未发现

**Comment by Lanly109** [comment]
看看`Pillow`库的版本是不是8.0+？如果是的话可以升级到9.0+，比如9.3.0

后台也没有报warning吗？

**Comment by ciriue** [comment]
确实是pillow的问题，谢谢大佬了
