### ISSUE TITLE
关于我老婆指令

### ISSUE THREAD

**Issue by Fhm-newbie** [Lanly109/headimg_generator#25]
![Screenshot_20221129_193906_com tencent mobileqq](https://user-images.githubusercontent.com/63446200/204520666-77f3eb86-81cb-464a-a3cd-ebd59a6ae860.jpg)

![Screenshot_20221129_193902_com tencent mobileqq](https://user-images.githubusercontent.com/63446200/204520672-344c91a1-53b1-4c85-9b2f-2cdac00301c2.jpg)
大佬。。。 我老婆 指令对图片使用的话默认为male。。。有办法改吗？

**Comment by Fhm-newbie** [comment]
应该是对图片判定没有获取到gender，导致了确实gender != female然后就变成了老公了

**Comment by Fhm-newbie** [comment]
应该是对图片判定没有获取到gender，导致了确实gender != female然后就变成了老公了

**Comment by Lanly109** [comment]
有道理，晚点我改改，感谢您的建议
