### ISSUE TITLE
无法加载 resources 下 fonts 字体

### ISSUE THREAD

**Issue by clacknya** [Lanly109/headimg_generator#29]
在根目录代码中似乎找不到有加载字体的实现，仅在 [nonebot_plugin_imageutils/fonts.py](https://github.com/Lanly109/headimg_generator/blob/5b3cf9502e621bf192a213a637e8721f944a0d9b/nonebot_plugin_imageutils/fonts.py) 中找到。

同时代码中有多处错误，使用 `/` 号拼接字符串，例如

https://github.com/Lanly109/headimg_generator/blob/3ea26f3abe33788b9432a85b3a50f56601fc3c65/nonebot_plugin_imageutils/fonts.py#L43-L44

https://github.com/Lanly109/headimg_generator/blob/3ea26f3abe33788b9432a85b3a50f56601fc3c65/download.py#L74-L75

**Comment by Lanly109** [comment]
加载字体的确实是在`fonts.py`里。

关于字符串拼接的，`FONT_PATH`和`data_path`都是`pathlib`包里的`Path`类型，是支持`/`拼接字符串的。

**Comment by clacknya** [comment]
> 加载字体的确实是在`fonts.py`里。
> 
> 关于字符串拼接的，`FONT_PATH`和`data_path`都是`pathlib`包里的`Path`类型，是支持`/`拼接字符串的。

我这边处理中文字符就找不到字体，打了 print 也没有发现加载到字体。后面有空 debug 看看吧。

`\` 我是看类型标注是 `str`，没注意是 `Path` （

**Comment by Lanly109** [comment]
可以拉取下最新提交，我才发现获取自定义字体的路径有点问题，不好意思。
不过插件本身也会从系统字体库查找是否有对应字体，因为我用的是系统自带的字体，所以没有发觉到。

**Comment by clacknya** [comment]
最新版本已经修复了，可以正常加载了。
