### ISSUE TITLE
httpcore 与 httpx 需求 h11 冲突

### ISSUE THREAD

**Issue by Ayusummer** [Lanly109/headimg_generator#3]
![image](https://user-images.githubusercontent.com/59549826/169822217-59ee5be8-5b25-421b-8c0c-74440a545a71.png)

将 httpx 的版本改到 0.22.0(当前最新版本) 后无冲突

**Comment by Lanly109** [comment]
好的，我自己服务器上的`httpcore`是`0.9.1`没依赖问题，如果`httpx`是`0.22.0`也没问题的话我改改。感谢反馈。
