### ISSUE TITLE
无法显示文字

### ISSUE THREAD

**Issue by Felix010525** [Lanly109/headimg_generator#30]
头像表情包列表以及生成的图片内的汉字全都无法显示，麻烦佬看看orz
![689e79e82cc4c2ca.jpg](https://user-images.githubusercontent.com/115688756/218672879-1f89613d-e73c-42be-86a5-4465b1d84933.jpg)![-5ab72596e34eb0c0.jpg](https://user-images.githubusercontent.com/115688756/218672953-f0c03f03-712d-41b2-9e86-23c8fc74f5fc.jpg)
![-2a1485b0b2fbea11.jpg](https://user-images.githubusercontent.com/115688756/218673095-397dc921-6b76-4dc1-b886-01ed7e0934eb.jpg)

**Comment by Felix010525** [comment]
之前2022.11.15的版本是表情包列表能显示，但是出的图片里文字无法显示，更新之后都没法显示了

**Comment by Lanly109** [comment]
你好，你可以拉一下最新的代码，之前获取自定义字体的路径有点问题，现在修复了。

它使用的字体定义在 [nonebot_plugin_imageutils/config.py](https://github.com/Lanly109/headimg_generator/blob/main/nonebot_plugin_imageutils/config.py#L6)，从上往下依次查找是否有对应字体。查找范围除了自定义路径（即`resources/fonts`下），还会查找系统的字体库。
关于缺失的字体，可以参考[nonebot_plugin_imageutils的README](https://github.com/noneplugin/nonebot-plugin-imageutils)，通过`yum`安装。

**Comment by Felix010525** [comment]
阿里嘎多！佬辛苦了
