### ISSUE TITLE
在首次安装生成config.yml后再次启动hoshino时出现报错

### ISSUE THREAD

**Issue by FanJZSS** [Lanly109/headimg_generator#39]
[error.log](https://github.com/Lanly109/headimg_generator/files/11992417/error.log)
还请大佬看看

**Comment by Lanly109** [comment]
看着感觉是`pyyaml`的版本问题。
但我服务器上`pip list | grep yaml`后的只看到了
`pyyaml_env_tag                    0.1`
可以尝试下低版本的`pyyaml`？

**Comment by FanJZSS** [comment]
> 

安装了`pyyaml_env_tag`后启动无报错了，感谢大佬

**Comment by Xruoji** [comment]
能问下装的哪个版本吗？

**Comment by duoshoumiao** [comment]
我也是一直报错  服务列表没有 头像表情包

**Comment by duoshoumiao** [comment]
> > 
> 
> 安装了`pyyaml_env_tag`后启动无报错了，感谢大佬

怎么修复的？

**Comment by duoshoumiao** [comment]
![image](https://github.com/Lanly109/headimg_generator/assets/94856184/a4a48b62-22f9-48d2-b70c-f04a687c1309)
