### ISSUE TITLE
能否像以前一样增加回复触发？

### ISSUE THREAD

**Issue by rockqtmh** [Lanly109/headimg_generator#40]
我记得整合文字表情包前的版本是可以回复触发的，不知能否加上这个功能？

**Comment by Lanly109** [comment]
现在也是可以回复触发的？
<img width="436" alt="image" src="https://github.com/Lanly109/headimg_generator/assets/32431960/9cd2c2b6-fc40-4815-af74-a41aeb4154e9">

**Comment by rockqtmh** [comment]
不好意思，提问时脑抽了。我的意思是：现在回复触发必须要参数正好才能成功，能不能像以前一样按一个默认顺序取图片生成表情

**Comment by Lanly109** [comment]
好像不太明白是什么意思（指的是会有一张默认照片是bot的头像吗？

**Comment by Lanly109** [comment]
明白你的意思了
