### ISSUE TITLE
resources.zip 在哪里呀

### ISSUE THREAD

**Issue by Lanly109** [Lanly109/headimg_generator#7]
请在release中下载resources.zip，并解压其放置于此目录。

这个 resources.zip 在哪里呀？

_Originally posted by @1055169799 in https://github.com/Lanly109/headimg_generator/issues/6#issuecomment-1146715474_

**Comment by Lanly109** [comment]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/32431960/172033243-63277693-4eaa-40f3-9ffe-e4717678adda.png">

在红圈标注的地方，[release](https://github.com/Lanly109/headimg_generator/releases)

**Comment by 1055169799** [comment]
> <img width="1319" alt="image" src="https://user-images.githubusercontent.com/32431960/172033243-63277693-4eaa-40f3-9ffe-e4717678adda.png">
> 
> 在红圈标注的地方，[release](https://github.com/Lanly109/headimg_generator/releases)

好的，谢谢
